### ISSUE TITLE
Getting Started documents have Guides top menu highlighted

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkusio.github.io#105]
When clicking on Creating Your First Application / Building Native Images / Using our Tooling in Get Started section user is switched to Guides section (Guides is highlighted in top menu)

Those 3 guides could have Get Started top menu item highlighted.

**Comment by gekorob** [comment]
Hi,
  I think it's because the *_includes/templates/header-navigation.html* set the *active* class on the Get Started using the following:

```html
<a href="{{site.baseurl}}/get-started/" class="{% if page.url contains '/get-started/' %}active{% endif %}">Get Started</a>
```

All the Get Started side bar links point to the content using the link */guides* so the navbar Guides link is active (highlighted).

A quick but not elegant fix could be to better specify the test that assign the class active. 
Another one could be to create a *get-started* folder into the content structure.

**Comment by maxandersen** [comment]
I'm not really following the issue here. 

The Getting Started section is about Getting you started and eventually there will be links from there to other parts of the site, i.e. guide under the Guides section.

Thus I would classify this as working as expected ?

**Comment by rsvoboda** [comment]
These guides are mentioned in Get Started section but are not listed in Guides section
    Be Guided Through First Application
    Quickly Bootstrap Your Application
    Building Native Images
    Using our Tooling

https://quarkus.io/guides/ explicitly mentions Getting Started guides.

I would classify this as minor issue ;)

**Comment by maxandersen** [comment]
ah - missed that they were listed differently...gotcha :)
