### ISSUE TITLE
Panache streams example not quite right

### ISSUE THREAD

**Issue by jamesfalkner** [quarkusio/quarkusio.github.io#163]
At https://quarkus.io/guides/hibernate-orm-panache-guide there is a snippet for streams:

```
List<String> namesButEmmanuels = Person.streamAll()
    .map(p -> p.name.toLowerCase() )
    .filter( n -> ! "emmanuel".equals(n) )
    .collect(Collectors.toList());
```

But it doesn't work due to no type information for the stream. It needs to be

```
List<String> namesButEmmanuels = Person.<Person>streamAll()
    .map(p -> p.name.toLowerCase() )
    .filter( n -> ! "emmanuel".equals(n) )
    .collect(Collectors.toList());
```

Thanks to @dmlloyd for the help!

**Comment by dmlloyd** [comment]
It might also depend on the JDK as different Java versions have different powers of inference.

**Comment by gsmet** [comment]
@FroMage have you seen this one? If it's true then there might be something to fix in Panache itself? It looks like something for which we shouldn't need the `<Person>` addition.

**Comment by FroMage** [comment]
No, we can't fix it due to how type inference works. `Stream<Person> s = Person.sreamAll()` works, and you would think that for the same reason (left-hand-side inference) this ought to work: `Person.sreamAll().map((Person p) -> p.name.toLowerCase())` but no, because the argument to `map` is not used to infer the type of `Person.streamAll()`.

There's only so much magic we can do to trick Java's type inference limitations. We should fix the guide.

**Comment by FroMage** [comment]
WDYT of https://github.com/quarkusio/quarkus/pull/2077 ? I think it's nicer than `Person.<Person>.streamAll()`.
